version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: >
        ssh -oStrictHostKeyChecking=no ubuntu@hls-converter.com "
        cd hls-converter-api; 
        git pull;
        docker-compose build;
        docker-compose up -d;"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master

 

